#!/usr/bin/env bash
python3 process_dictionary.py xaa &
python3 process_dictionary.py xab &
python3 process_dictionary.py xac &
python3 process_dictionary.py xad &
python3 process_dictionary.py xae &
python3 process_dictionary.py xaf &
python3 process_dictionary.py xag &
python3 process_dictionary.py xah &
python3 process_dictionary.py xai &
python3 process_dictionary.py xaj &
python3 process_dictionary.py xak &
python3 process_dictionary.py xal &
python3 process_dictionary.py xam &
python3 process_dictionary.py xan &
python3 process_dictionary.py xao &
python3 process_dictionary.py xap &
python3 process_dictionary.py xaq &
python3 process_dictionary.py xar &
python3 process_dictionary.py xas &
python3 process_dictionary.py xat &
python3 process_dictionary.py xau &
python3 process_dictionary.py xav &
python3 process_dictionary.py xaw &
python3 process_dictionary.py xax &